site_name: ConfigX

nav:
  - Home:
    - "home/index.md"
    - Introduction:
      - Motivation: ""
      - Getting Started: "home/getting-started.md"
      - FAQ: ""
    - Features:
      - Validation: ""
      - Multi-sources: ""
      - Templating and Casting: ""
    - About:
      - Changelog: ""
      - Contributing: ""
      - License: ""

  - User Guides:
    - "user/index.md"
    - General:
      - How to do this: ""
      - How to do that: ""
      - Doing something: ""
    - Framework-specific:
      - Django:
        - Setup: ""
        - Using django: ""
      - Flask:
        - Setup: ""
        - Using flask: ""
      - FastApi:
        - Setup: ""
        - Using FastApi: ""

  - Reference:
    - For Users:
      - Setting Object: "user/reference/setting_object.md"
      - Validation: ""
      - Loaders: ""
      - Lazy Evaluation: ""
    - For devs:
      - Core:
        - "reference/setting_tree.md"
      - Services:
        - "reference/evaluation.md"
      - Public:
        - "reference/lib_shell.md"

  - Development: 
    - "dev/index.md"
    - Understanding the system: 
      - Overview: ""
      - Modules: ""
      - Data Flow: ""
      - Considerations: ""
    - Guides:
      - Documentation: ""
      - Tooling: ""
      - Code Standards: ""
      - Git workflows: ""
      - Testing: ""

theme:
  name: material
  features:
    - navigation.tabs 
    - navigation.sections 
    - navigation.indexes 
    # - navigation.expand 
    - navigation.path

markdown_extensions:

  # Python Markdown
  - admonition
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  # https://mkdocstrings.github.io/usage/
  - mkdocstrings

