[project]
name = "configx"
description = "Dynaconf re-write"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
  "pytest",
  "mkdocs-material",
  "mkdocstrings[python]",
  # "tox",
  # "pre-commit",
  # "bump2version"
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "src"
